---
# Storage provisioner to use
storage_provisioner: "local-path"

# local-path-provisioner settings
local_path_provisioner_version: "v0.0.26"
local_path_provisioner_namespace: "local-path-storage"
local_path_storage_path: "/opt/local-path-provisioner"

# Make local-path the default StorageClass
local_path_default_class: true
