{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mechanicbuddy-tenant.serviceAccountName" . }}
  namespace: tenant-{{ .Values.tenant.id }}
  labels:
    {{- include "mechanicbuddy-tenant.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
