# Generated Secrets - KEEP SECURE!
jwt_secret: iiJOl5NVWnLgelRlJflL9T424DrMpConHMefkm0DbSqnOHKevDyYjTwbawEjKjoR
consumer_secret: yT0ZMEr0Ma8iPB9vzHnem61ErXWb3HKe
session_secret: kUIlKDZhKtLE5go0c8zRc5KUPOsyaZqh
postgres_superuser_password: UUFrsiSpkYzVz4RH3WnnDw6N
postgres_management_password: 1UoR0hAfRceRKwRoY1KRoGJg
postgres_freetier_password: 2l7Fs0yiB9Uw4qlSqHNTPbhW
